name: CI
# Triggers
on:
  workflow_dispatch: # Manual trigger from the Actions tab
  push:
    branches:
      - '**'
permissions:
  contents: write
  packages: write
  pages: write
  actions: write

jobs:
  ci:
    uses: pingmyheart/Ping-Actions/.github/workflows/dispatch.yml@main
    secrets: inherit
    with:
      project-type: docker-maven
      java-version: 17