name: CI
# Triggers
on:
  workflow_dispatch: # Manual trigger from the Actions tab
  push:
    branches:
      - '**'
jobs:
  ci:
    secrets: inherit
    uses: pingmyheart/Ping-Action/.github/workflows/dispatch.yml@main
    with:
      project-type: docker-maven
      java-version: 17